name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-18.04
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              cxx: [g++-7, g++-8]
        env:
          CXX: ${{ matrix.cxx }}
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: Install Dependencies
          run: ./installDependencies.sh
        - name: Set up Build
          run: |
            mkdir build
            cd build
            cmake ..
        - name: Build
          run: |
            cd build
            make -j$(nproc)

